<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            [
                'name'       => 'Soyuducu təmiri',
                'slug'       => 'soyuducu-temiri',
                'icon'       => '🧊',
                'description'=> 'Bütün marka soyuducuların diaqnostikası və təmiri.',
                'hero_desc'  => 'Bütün marka soyuducuların peşəkar diaqnostikası və təmiri. Kompressor dəyişimi, qaz doldurma, termostat, fan mühərriki — hər növ xarabı aradan qaldırırıq.',
                'price_from' => 25,
                'sort_order' => 1,
                'problems'   => [
                    ['icon'=>'🌡️','title'=>'Soyutmur',        'desc'=>'Kompressor xarabı, freon sızması, termostat problemi.'],
                    ['icon'=>'🔊','title'=>'Səs-küy edir',      'desc'=>'Fan mühərriki xarabı, kompressor titrəməsi, buzlama.'],
                    ['icon'=>'💧','title'=>'Su axıdır',          'desc'=>'Drenaj borusu bəndliyi, qapı sızdırmazlığı pozulması.'],
                    ['icon'=>'🧊','title'=>'Buzlanma artıqdır',  'desc'=>'Termostat, defrost sistemi xarabı.'],
                    ['icon'=>'💡','title'=>'İşıq yanmır',        'desc'=>'Daxili lampa, açar, elektrik kontakt problemi.'],
                    ['icon'=>'🚪','title'=>'Qapı bağlanmır',     'desc'=>'Rezin contalar köhnəlmiş, menteşə xarabı.'],
                ],
                'brands'     => ['Samsung','LG','Bosch','Beko','Arçelik','Siemens','Indesit','Whirlpool','Electrolux','Gorenje','Liebherr','Atlant'],
                'faqs'       => [
                    ['q'=>'Soyuducu niyə soyutmur?',       'a'=>'Əsas səbəblər: kompressor xarabı, freon sızması, termostat problemi, fan dayanıb. Diaqnostika ilə dəqiq müəyyən edirik.'],
                    ['q'=>'Təmir nə qədər çəkir?',          'a'=>'Əksər hallarda 1-2 saata tamamlanır. Kompressor kimi böyük işlər 2-4 saat çəkə bilər.'],
                    ['q'=>'Diaqnostika pulsuzdurmu?',        'a'=>'Bəli, tamamilə pulsuzdur. Siz razı olmadıqca heç bir ödəniş tələb edilmir.'],
                    ['q'=>'Freon doldurmaq mümkündürmü?',    'a'=>'Bəli, R134a, R600a, R290 növü qazları doldururuq. Əvvəl sızma aşkarlanır.'],
                    ['q'=>'Zəmanət verirsinizkmi?',          'a'=>'Bəli, 12 aylıq yazılı zəmanət verilir.'],
                ],
            ],
            [
                'name'       => 'Qazan təmiri',
                'slug'       => 'qazan-temiri',
                'icon'       => '🔥',
                'description'=> 'Qaz, elektrik və kombineli qazanların peşəkar təmiri.',
                'hero_desc'  => 'Qaz, elektrik və kombineli qazanların peşəkar diaqnostikası və təmiri. Isıtma sisteminizin etibarlı işi üçün sertifikatlı ustalar xidmətinizdədir.',
                'price_from' => 30,
                'sort_order' => 2,
                'problems'   => [
                    ['icon'=>'🌡️','title'=>'Isıtmır',          'desc'=>'Yanma kamerası, qızdırıcı element, termostat xarabı.'],
                    ['icon'=>'📉','title'=>'Təzyiq düşür',       'desc'=>'Su sızması, genişlənmə qabı, relyef klapan problemi.'],
                    ['icon'=>'🔥','title'=>'Pilot yanmır',       'desc'=>'Elektrod, ionizasiya sensoru, qaz klapanı xarabı.'],
                    ['icon'=>'🔊','title'=>'Səs-küy edir',       'desc'=>'Nasos, hava yığılması, kir-pas birikməsi.'],
                    ['icon'=>'⚠️','title'=>'Xəta kodu',          'desc'=>'Sensor xarabı, elektron lövhə problemi.'],
                    ['icon'=>'💧','title'=>'Su sızır',           'desc'=>'Fitinqlər, istilik mübadiləçisi, contalar.'],
                ],
                'brands'     => ['Ariston','Baxi','Vaillant','Bosch','Buderus','Protherm','Immergas','Ferroli','De Dietrich','Viessmann'],
                'faqs'       => [
                    ['q'=>'Qazan niyə isitmır?',            'a'=>'Yanma kamerası, termostat, istilik mübadiləçisi, nasos və ya qaz klapanı xarab ola bilər.'],
                    ['q'=>'Qaz qazan təhlükəlidirmi?',       'a'=>'Qaz sızması varsa dərhal qazan açarını bağlayın, pəncərəni açın, bizimlə əlaqə saxlayın.'],
                    ['q'=>'Elektrik qazanı da təmir edirsinizmi?', 'a'=>'Bəli, həm qaz, həm elektrik, həm kombineli qazanlar.'],
                    ['q'=>'Diaqnostika pulsuzdurmu?',        'a'=>'Bəli, tamamilə pulsuzdur.'],
                    ['q'=>'Zəmanət verirsinizkmi?',          'a'=>'Bəli, 12 aylıq yazılı zəmanət verilir.'],
                ],
            ],
            [
                'name'       => 'Su sızması aşkarlanması',
                'slug'       => 'su-sizmasi',
                'icon'       => '💧',
                'description'=> 'Termal kamera ilə gizli su sızmalarının aşkarlanması.',
                'hero_desc'  => 'Müasir termal kamera və akustik detektorlarla gizli su sızmalarını divara zərər vermədən aşkarlayırıq. Kranlar, borular, döşəmə altı — hər yerdə.',
                'price_from' => 20,
                'sort_order' => 3,
                'problems'   => [
                    ['icon'=>'🔍','title'=>'Gizli sızma',        'desc'=>'Termal kamera ilə divara zərər vermədən gizli boru sızmalarını tapırıq.'],
                    ['icon'=>'🚰','title'=>'Damcılayan kran',     'desc'=>'Cartridge, conta, kran başlığı dəyişimi.'],
                    ['icon'=>'💥','title'=>'Boru partlaması',     'desc'=>'Fövqəladə müdaxilə, boru kəsimi, qovşaq dəyişimi.'],
                    ['icon'=>'📉','title'=>'Aşağı təzyiq',        'desc'=>'Magistral boru tıxanıqlığı, klapan, filtr bəndliyi.'],
                    ['icon'=>'🏠','title'=>'Döşəmə nəmdir',       'desc'=>'Döşəmə altı boru sızması, korroziya.'],
                    ['icon'=>'🧱','title'=>'Divar nəmlənir',      'desc'=>'Boru sızması, sızdırmazlıq pozulması.'],
                ],
                'brands'     => ['Grohe','Hansgrohe','Vitra','Ideal Standard','Geberit','Roca','Jacob Delafon'],
                'faqs'       => [
                    ['q'=>'Sızmanı necə aşkarlayırsınız?',   'a'=>'Termal kamera, akustik detektor ilə divara zərər vermədən.'],
                    ['q'=>'Divarı açmaq lazım olurmu?',       'a'=>'Müasir avadanlıqla çox hallarda divara ziyan vermədən tapılır.'],
                    ['q'=>'Fövqəladə hallarda neçəyə gəlirsiz?','a'=>'Boru partlaması halında 1 saata qədər gəlirik.'],
                    ['q'=>'Zəmanət verirsinizkmi?',           'a'=>'Bəli, 12 aylıq yazılı zəmanət.'],
                ],
            ],
            [
                'name'       => 'Paltar maşını təmiri',
                'slug'       => 'paltar-masini',
                'icon'       => '👕',
                'description'=> 'Avtomatik paltar maşınlarının hər növ xarabının aradan qaldırılması.',
                'hero_desc'  => 'Avtomatik paltar maşınlarının bütün növ xarablarının peşəkar aradan qaldırılması. Dayaq yatağı, qayış, mühərrik, elektron lövhə — hamısını təmir edirik.',
                'price_from' => 25,
                'sort_order' => 4,
                'problems'   => [
                    ['icon'=>'🔄','title'=>'Fırlanmır',          'desc'=>'Qayış qırılması, mühərrik xarabı, tacho-generator problemi.'],
                    ['icon'=>'🚿','title'=>'Su axıtmır',          'desc'=>'Nasos bənd, filtr kirli, klapan xarabı.'],
                    ['icon'=>'⚠️','title'=>'Xəta kodu',           'desc'=>'Elektron lövhə, sensor xarabı, proqram problemi.'],
                    ['icon'=>'📳','title'=>'Titrəyir / Səs edir', 'desc'=>'Dayaq yatağı, amortizator, kontrçəki xarabı.'],
                    ['icon'=>'💧','title'=>'Su götürmür',          'desc'=>'Su klapanı xarabı, şlanq əyilmiş.'],
                    ['icon'=>'🔒','title'=>'Qapı açılmır',        'desc'=>'UBL kilidi, qapı qolu, elektron blok xarabı.'],
                ],
                'brands'     => ['Samsung','LG','Bosch','Beko','Arçelik','Indesit','Candy','Hotpoint','Whirlpool','Miele','Siemens','Electrolux'],
                'faqs'       => [
                    ['q'=>'Paltar maşını niyə fırlanmır?',   'a'=>'Qayış qırılması, mühərrik xarabı, tacho-generator problemi.'],
                    ['q'=>'Dayaq yatağı dəyişimi mümkündürmü?','a'=>'Bəli, bütün marka maşınlarda dayaq yatağı dəyişimi aparılır.'],
                    ['q'=>'Evdə təmir olunurmu?',             'a'=>'Bəli, demək olar ki bütün işlər birbaşa evinizde aparılır.'],
                    ['q'=>'Zəmanət verirsinizkmi?',           'a'=>'Bəli, 12 aylıq yazılı zəmanət.'],
                ],
            ],
            [
                'name'       => 'Televizor təmiri',
                'slug'       => 'televizor-temiri',
                'icon'       => '📺',
                'description'=> 'LCD, LED, OLED televizorların diaqnostikası və təmiri.',
                'hero_desc'  => 'Bütün marka televizorların diaqnostikası, matris dəyişimi, LED arxa işıqlandırma, güc bloku, audio sistemi, Smart TV problemi — hamısını həll edirik.',
                'price_from' => 20,
                'sort_order' => 5,
                'problems'   => [
                    ['icon'=>'🖥️','title'=>'Şəkil yoxdur',      'desc'=>'LED arxa işıqlandırma, matris xarabı, video kartı.'],
                    ['icon'=>'🔇','title'=>'Ses gəlmir',          'desc'=>'Dinamik, audio çip, səs sxemi xarabı.'],
                    ['icon'=>'⚡','title'=>'Açılmır',             'desc'=>'Güc bloku, kondensator, elektron lövhə xarabı.'],
                    ['icon'=>'🔌','title'=>'HDMI işləmir',        'desc'=>'HDMI konnektoru yanmış, daxili port xarabı.'],
                    ['icon'=>'💥','title'=>'Ekran qırılıb',       'desc'=>'LCD/LED matris dəyişimi — bütün ölçülərdə.'],
                    ['icon'=>'📱','title'=>'Smart TV problemi',   'desc'=>'Firmware yeniləmə, hesab girişi, proqram sıfırlama.'],
                ],
                'brands'     => ['Samsung','LG','Sony','Philips','Panasonic','TCL','Hisense','Vestel','Sharp','Toshiba'],
                'faqs'       => [
                    ['q'=>'Ekranı dəyişmək nə qədər başa gəlir?','a'=>'Matris ölçüsündən asılıdır. Diaqnostika ilə dəqiq qiymət bildiririk.'],
                    ['q'=>'Smart TV problemi düzəldilirmi?',  'a'=>'Bəli, firmware yeniləmə, Netflix/YouTube, WiFi — hamısı.'],
                    ['q'=>'Zəmanət verirsinizkmi?',           'a'=>'Bəli, 12 aylıq yazılı zəmanət.'],
                ],
            ],
            [
                'name'       => 'Kondisioner təmiri',
                'slug'       => 'kondisioner',
                'icon'       => '❄️',
                'description'=> 'Split sistemlərin quraşdırılması, freon doldurma, filtr baxımı.',
                'hero_desc'  => 'Split sistemlərin quraşdırılması, qaz doldurma, filtr təmizlənməsi, kompressor dəyişimi — bütün kondisioner xidmətləri bir yerdə.',
                'price_from' => 25,
                'sort_order' => 6,
                'problems'   => [
                    ['icon'=>'🌡️','title'=>'Soyutmur/Qızdırmır','desc'=>'Freon sızması, kompressor xarabı, termostat problemi.'],
                    ['icon'=>'💨','title'=>'Qaz doldurma',        'desc'=>'R410A, R32, R22 növü freon doldurma xidməti.'],
                    ['icon'=>'💧','title'=>'Damlayır',            'desc'=>'Drenaj borusu bənd, nasos xarabı, quraşdırma problemi.'],
                    ['icon'=>'🔊','title'=>'Səs-küy edir',        'desc'=>'Fan qanadları, dayaq yatağı, vibrasiya yastığı.'],
                    ['icon'=>'⚠️','title'=>'Xəta kodu',           'desc'=>'Sensor, termistor, elektron lövhə xarabı.'],
                    ['icon'=>'🧹','title'=>'Filtr baxımı',        'desc'=>'Profilaktik baxım, filtr yuma, sistem dezinfeksiyası.'],
                ],
                'brands'     => ['Mitsubishi','Daikin','Gree','Midea','Samsung','LG','Haier','Electra','Carrier','Toshiba'],
                'faqs'       => [
                    ['q'=>'Kondisioner niyə soyutmur?',      'a'=>'Freon sızması, kompressor xarabı, kirli filtr, sensor problemi.'],
                    ['q'=>'Neçə vaxtdan bir filtr yuyulmalıdır?','a'=>'2-3 ayda bir dəfə. İldə bir dəfə peşəkar baxım tövsiyə olunur.'],
                    ['q'=>'Yeni kondisioner quraşdırılırmı?', 'a'=>'Bəli, yeni split sistemin quraşdırılması xidməti də göstəririk.'],
                    ['q'=>'Zəmanət verirsinizkmi?',           'a'=>'Bəli, 12 aylıq yazılı zəmanət.'],
                ],
            ],
            [
                'name'       => 'Qabyuyan maşın təmiri',
                'slug'       => 'qabyuyan-masin',
                'icon'       => '🍽️',
                'description'=> 'Qabyuyan maşınların peşəkar diaqnostikası və təmiri.',
                'hero_desc'  => 'Bütün marka qabyuyan maşınların diaqnostikası, su kəsimi, nasos, qapı kilidi, elektron lövhə — hər növ xarabı aradan qaldırırıq.',
                'price_from' => 25,
                'sort_order' => 7,
                'problems'   => [
                    ['icon'=>'🍽️','title'=>'Yaxşı yumur',        'desc'=>'Suyun sirkulyasiyası, nasosun zəifləməsi, filtr tıxanıqlığı.'],
                    ['icon'=>'🚿','title'=>'Su axıtmır',           'desc'=>'Drenaj nasosu, filtri bənd, şlanq tıxanmış.'],
                    ['icon'=>'🚪','title'=>'Qapı bağlanmır',      'desc'=>'Qapı kilidi (latch) xarabı, menteşə deformasiyası.'],
                    ['icon'=>'⚠️','title'=>'Xəta kodu',           'desc'=>'Elektron lövhə, sensor xarabı — bütün markalar.'],
                    ['icon'=>'💧','title'=>'Su sızır',            'desc'=>'Qapı contu, şlanq birləşmələri, nasos sızdırması.'],
                    ['icon'=>'🧼','title'=>'Dərman götürmür',     'desc'=>'Yuyucu dispenser (verilən bölmə) xarabı.'],
                ],
                'brands'     => ['Bosch','Siemens','Beko','Arçelik','Samsung','LG','Indesit','Candy','Hotpoint','Miele'],
                'faqs'       => [
                    ['q'=>'Qabyuyan maşın su axıtmırsa nə etməli?','a'=>'Drenaj nasosu, filtr və şlanq yoxlanılmalıdır. Diaqnostika ilə dəqiq müəyyən edirik.'],
                    ['q'=>'Evdə təmir olunurmu?',             'a'=>'Bəli, demək olar ki bütün işlər birbaşa evinizde aparılır.'],
                    ['q'=>'Zəmanət verirsinizkmi?',           'a'=>'Bəli, 12 aylıq yazılı zəmanət.'],
                ],
            ],
            [
                'name'       => 'Santexnika',
                'slug'       => 'santexnika',
                'icon'       => '🔧',
                'description'=> 'Kran, tualet, boru, drenaj xəttlərinin quraşdırılması və təmiri.',
                'hero_desc'  => 'Ev santexnikasının bütün növ quraşdırma və təmir işləri. Kranlar, tualet, duş, boru sistemi, drenaj — sürətli və keyfiyyətli xidmət.',
                'price_from' => 20,
                'sort_order' => 8,
                'problems'   => [
                    ['icon'=>'🚰','title'=>'Damcılayan kran',     'desc'=>'Cartridge, conta, kran başlığı dəyişimi — hər növ kran.'],
                    ['icon'=>'🚽','title'=>'Tualet problemi',      'desc'=>'Sifonun dəyişimi, su kəsmə, çəkdirmə problemi.'],
                    ['icon'=>'📉','title'=>'Aşağı su təzyiqi',    'desc'=>'Magistral problem, klapan, filtr tıxanıqlığı.'],
                    ['icon'=>'🔗','title'=>'Boru dəyişimi',       'desc'=>'Polipropilen, metal-plastik, mis boru montajı.'],
                    ['icon'=>'🚿','title'=>'Duş kabin quraşdırma','desc'=>'Müxtəlif tip duş kabinlərinin montajı.'],
                    ['icon'=>'🏠','title'=>'Sanitariya quraşdırma','desc'=>'Yeni ev əşyalarının (lavabo, vanna) quraşdırılması.'],
                ],
                'brands'     => ['Grohe','Hansgrohe','Vitra','Ideal Standard','Roca','Geberit','Duravit','Cersanit'],
                'faqs'       => [
                    ['q'=>'Fövqəladə hallarda neçəyə gəlirsiz?', 'a'=>'Boru partlaması halında 1 saata qədər gəlirik.'],
                    ['q'=>'Yeni ev üçün santexnika quraşdırılırmı?','a'=>'Bəli, tam sanitariya quraşdırma xidmətimiz var.'],
                    ['q'=>'Zəmanət verirsinizkmi?',           'a'=>'Bəli, 12 aylıq yazılı zəmanət.'],
                ],
            ],
            [
                'name'       => 'Elektrik işləri',
                'slug'       => 'elektrik-isleri',
                'icon'       => '⚡',
                'description'=> 'Rozetka, açar, elektrik panelininin montajı və elektrik xətlərinin çəkilməsi.',
                'hero_desc'  => 'Ev elektrik sisteminin bütün növ işləri. Rozetka, açar, elektrik tablosu, kabel çəkilişi, işıqlandırma — sertifikatlı elektrikçilər tərəfindən.',
                'price_from' => 20,
                'sort_order' => 9,
                'problems'   => [
                    ['icon'=>'🔌','title'=>'Rozetka işləmir',     'desc'=>'Kontakt xarabı, kabel qırılması, sigorta atması.'],
                    ['icon'=>'💡','title'=>'Açar xarabı',         'desc'=>'Sadə, dimmer, ağıllı açarların montajı və təmiri.'],
                    ['icon'=>'⚡','title'=>'Sigorta atır',         'desc'=>'Elektrik yükü hesablanması, sigorta blokunun yenilənməsi.'],
                    ['icon'=>'🔦','title'=>'İşıqlandırma',        'desc'=>'LED, spotlar, lusstra, xarici işıqlandırmanın montajı.'],
                    ['icon'=>'📟','title'=>'Elektrik tablosu',     'desc'=>'Pano montajı, kabellərin yenidən bağlanması.'],
                    ['icon'=>'🏗️','title'=>'Kabel çəkilişi',      'desc'=>'Yeni elektrik xətlərinin gizli/açıq çəkilişi.'],
                ],
                'brands'     => ['Legrand','Schneider','ABB','Siemens','Gewiss','Hager','ETI','Novatek'],
                'faqs'       => [
                    ['q'=>'Elektrik işlərini özüm görə bilərəmmi?','a'=>'Elektrik işlərini peşəkara həvalə etmək tövsiyə olunur. Yanlış bağlantı yanğın təhlükəsi yaradır.'],
                    ['q'=>'Ev üçün enerji hesablanması aparılırmı?','a'=>'Bəli, elektrik yükü hesablanması xidmətimiz var.'],
                    ['q'=>'Zəmanət verirsinizkmi?',           'a'=>'Bəli, 12 aylıq yazılı zəmanət.'],
                ],
            ],
            [
                'name'       => 'Ocaq təmiri',
                'slug'       => 'ocaq-temiri',
                'icon'       => '🍳',
                'description'=> 'Qaz və elektrik plitələrinin bütün xarablarının professional təmiri.',
                'hero_desc'  => 'Qaz və elektrik ocaqlarının, sobalarının diaqnostikası və təmiri. Yanıcı, ocaq başlığı, termostat, fırın spirali — bütün xarablar aradan qaldırılır.',
                'price_from' => 25,
                'sort_order' => 10,
                'problems'   => [
                    ['icon'=>'🔥','title'=>'Alovlanmır',          'desc'=>'Elektrod xarabı, qaz klapanı, ionizasiya sensoru problemi.'],
                    ['icon'=>'🌡️','title'=>'Fırın qızdırmır',    'desc'=>'Qızdırıcı spiral, termostat, temperatur sensoru xarabı.'],
                    ['icon'=>'⚠️','title'=>'Qaz iyi gəlir',       'desc'=>'Dərhal istifadəni dayandırın, ustanı çağırın.'],
                    ['icon'=>'💡','title'=>'İşıq yanmır',         'desc'=>'Fırın lampası, açar, elektrik kontakt problemi.'],
                    ['icon'=>'🖥️','title'=>'Panel xarabı',        'desc'=>'Elektron idarəetmə paneli, düymə xarabı.'],
                    ['icon'=>'🧹','title'=>'Yanğın seçici bənd',  'desc'=>'Ocaq burnerinin təmizlənməsi, sıxılmış deşiklərin açılması.'],
                ],
                'brands'     => ['Bosch','Siemens','Beko','Arçelik','Samsung','LG','Indesit','Gorenje','Whirlpool','Electrolux'],
                'faqs'       => [
                    ['q'=>'Ocaq alovlanmırsa nə etməli?',    'a'=>'Elektrod, qaz klapanı, ionizasiya sensoru yoxlanılmalıdır.'],
                    ['q'=>'Qaz iyi gəlirsə?',                'a'=>'Dərhal ocağı söndürün, pəncərəni açın, qaz şirkətinə və bizə zəng edin.'],
                    ['q'=>'Zəmanət verirsinizkmi?',          'a'=>'Bəli, 12 aylıq yazılı zəmanət.'],
                ],
            ],
            [
                'name'       => 'Mebel təmiri',
                'slug'       => 'mebel-temiri',
                'icon'       => '🪑',
                'description'=> 'Kuxna, yataq otağı, qonaq otağı mebelinin bərpası.',
                'hero_desc'  => 'Ev mebelinin peşəkar bərpası və yenilənməsi. Menteşə, çekmece rayları, döşəmə bərpası, montaj — keyfiyyətli materiallarla.',
                'price_from' => 20,
                'sort_order' => 11,
                'problems'   => [
                    ['icon'=>'🔩','title'=>'Menteşə xarabı',      'desc'=>'Dolap, şüşəlik, kuxna qapısı menteşəsinin dəyişimi.'],
                    ['icon'=>'📦','title'=>'Çekmece işləmir',     'desc'=>'Rayların dəyişimi, sürüşmə sisteminin bərpası.'],
                    ['icon'=>'🪑','title'=>'Kreslo/stul xarabı',  'desc'=>'Qol dayağı, mexanizm, parça örtüyü bərpası.'],
                    ['icon'=>'🛏️','title'=>'Çarpayı mexanizmi',   'desc'=>'Əsas, liftin mexanizmi, xəlbiri sınıb.'],
                    ['icon'=>'🔨','title'=>'Yeni mebel montajı',  'desc'=>'Hazır mebelin yığılması — kuxna, garderob, şüşəlik.'],
                    ['icon'=>'🪵','title'=>'Cızıq/zərər bərpası', 'desc'=>'Laminat, qapı səthindəki cızıqların bərpası.'],
                ],
                'brands'     => ['IKEA','Bellona','İpek Mobilya','Kelebek','Doğtaş','Roma','Mondi','Yataş'],
                'faqs'       => [
                    ['q'=>'Evdə mebel bərpası aparılırmı?', 'a'=>'Bəli, demək olar ki bütün işlər birbaşa evinizde aparılır.'],
                    ['q'=>'Yeni IKEA mebeli yığılırmı?',    'a'=>'Bəli, hər növ hazır mebelinin montajı aparılır.'],
                    ['q'=>'Zəmanət verirsinizkmi?',         'a'=>'Bəli, 12 aylıq yazılı zəmanət.'],
                ],
            ],
            [
                'name'       => 'Digər xidmətlər',
                'slug'       => 'diger-xidmetler',
                'icon'       => '🏠',
                'description'=> 'Mikrodalğalı soba, ütü, tozsoran, blender və digər kiçik texnikanın təmiri.',
                'hero_desc'  => 'Kiçik məişət texnikasının bütün növ xarablarının aradan qaldırılması. Mikrodalğalı, ütü, tozsoran, blender, çaydan — hamısını təmir edirik.',
                'price_from' => 15,
                'sort_order' => 12,
                'problems'   => [
                    ['icon'=>'📡','title'=>'Mikrodalğalı soba',   'desc'=>'Isıtmır, fırlanmır, qığılcım çıxır, açılmır.'],
                    ['icon'=>'👔','title'=>'Ütü xarabı',          'desc'=>'Qızdırmır, buxar çıxmır, temperator tənzimləmir.'],
                    ['icon'=>'🌀','title'=>'Tozsoran',            'desc'=>'Sorma gücü azalıb, motor işləmir, filtr problemli.'],
                    ['icon'=>'🥤','title'=>'Blender/mixer',        'desc'=>'Motor xarabı, bıçaqlar dəyişdirmə, gövdə çatlaması.'],
                    ['icon'=>'☕','title'=>'Çaydan/kahvəmaşın',   'desc'=>'Isıtmır, kireçdən təmizlənmə, qapı contası.'],
                    ['icon'=>'🍞','title'=>'Tost/çörək bişirən',  'desc'=>'Spiral xarabı, termostat problemi, mexanizm sınıb.'],
                ],
                'brands'     => ['Samsung','LG','Bosch','Philips','Tefal','Rowenta','Moulinex','Braun','Dyson','Electrolux'],
                'faqs'       => [
                    ['q'=>'Kiçik texnikanı evdə təmir etmək olurmu?','a'=>'Bəzi kiçik texnikalar workshop-da, bəziləri evdə təmir olunur. Öncədən razılaşdırılır.'],
                    ['q'=>'Diaqnostika pulsuzdurmu?',        'a'=>'Bəli, tamamilə pulsuzdur.'],
                    ['q'=>'Zəmanət verirsinizkmi?',          'a'=>'Bəli, 12 aylıq yazılı zəmanət.'],
                ],
            ],
        ];

        foreach ($services as $data) {
            Service::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
