<?php

return [
    'sections' => [
        'Header və Footer' => [
            ['key' => 'page_title_services', 'label' => 'Meta title: Xidmətlər', 'default' => 'Bütün Xidmətlər'],
            ['key' => 'page_title_about', 'label' => 'Meta title: Haqqımızda', 'default' => 'Haqqımızda'],
            ['key' => 'page_title_contact', 'label' => 'Meta title: Əlaqə', 'default' => 'Əlaqə'],
            ['key' => 'page_title_portfolio', 'label' => 'Meta title: Portfolio', 'default' => 'Portfolio'],
            ['key' => 'ui_nav_services', 'label' => 'Menyu: Xidmətlər', 'default' => 'Xidmətlər'],
            ['key' => 'ui_nav_about', 'label' => 'Menyu: Haqqımızda', 'default' => 'Haqqımızda'],
            ['key' => 'ui_nav_portfolio', 'label' => 'Menyu: Portfolio', 'default' => 'Portfolio'],
            ['key' => 'ui_nav_how', 'label' => 'Menyu: Necə işləyir', 'default' => 'Necə işləyir'],
            ['key' => 'ui_nav_faq', 'label' => 'Menyu: FAQ', 'default' => 'FAQ'],
            ['key' => 'ui_nav_contact', 'label' => 'Menyu: Əlaqə', 'default' => 'Əlaqə'],
            ['key' => 'ui_order_btn', 'label' => 'Ümumi: Sifariş düyməsi', 'default' => 'Sifariş et'],
            ['key' => 'ui_footer_links_title', 'label' => 'Footer: Keçidlər başlığı', 'default' => 'Keçidlər'],
            ['key' => 'ui_footer_services_title', 'label' => 'Footer: Xidmətlər başlığı', 'default' => 'Xidmətlər'],
            ['key' => 'ui_footer_contact_title', 'label' => 'Footer: Əlaqə başlığı', 'default' => 'Əlaqə'],
            ['key' => 'ui_mobile_contact_title', 'label' => 'Mobil menyu əlaqə başlığı', 'default' => 'Bizimlə əlaqə saxlayın:'],
            ['key' => 'ui_footer_desc', 'label' => 'Footer təsvir', 'default' => 'Bakı şəhərinin ən etibarlı ev texnikası təmir xidməti. 4+ il təcrübə, 4000+ uğurlu sifariş.', 'type' => 'textarea'],
            ['key' => 'ui_label_address', 'label' => 'Ümumi etiket: Ünvan', 'default' => 'Ünvan'],
            ['key' => 'ui_label_phone', 'label' => 'Ümumi etiket: Telefon', 'default' => 'Telefon'],
            ['key' => 'ui_label_email', 'label' => 'Ümumi etiket: E-poçt', 'default' => 'E-poçt'],
            ['key' => 'ui_label_hours', 'label' => 'Ümumi etiket: İş saatları', 'default' => 'İş saatları'],
            ['key' => 'ui_float_whatsapp_title', 'label' => 'Float ikon title', 'default' => 'WhatsApp-a yazın'],
            ['key' => 'ui_footer_copyright', 'label' => 'Footer copyright', 'default' => '© :year USTA.BİZ.AZ — Bütün hüquqlar qorunur.'],
            ['key' => 'ui_footer_privacy', 'label' => 'Footer məxfilik', 'default' => 'Məxfilik siyasəti'],
            ['key' => 'ui_footer_terms', 'label' => 'Footer istifadə şərtləri', 'default' => 'İstifadə şərtləri'],
        ],

        'Ana Səhifə Form və Bildirişlər' => [
            ['key' => 'home_hero_trust_text', 'label' => 'Hero etibar mətni', 'default' => 'Son 7 gündə :count müştəriyə xidmət göstərdik'],
            ['key' => 'home_form_service_label', 'label' => 'Forma: Xidmət növü', 'default' => 'Xidmət növü'],
            ['key' => 'home_form_service_placeholder', 'label' => 'Forma: Xidmət seçin', 'default' => 'Xidmət seçin...'],
            ['key' => 'home_form_name_label', 'label' => 'Forma: Adınız', 'default' => 'Adınız'],
            ['key' => 'home_form_name_placeholder', 'label' => 'Forma: Ad Soyad', 'default' => 'Ad Soyad'],
            ['key' => 'home_form_phone_label', 'label' => 'Forma: Telefon', 'default' => 'Telefon *'],
            ['key' => 'home_form_address_label', 'label' => 'Forma: Ünvan', 'default' => 'Ünvan'],
            ['key' => 'home_form_address_placeholder', 'label' => 'Forma: Ünvan placeholder', 'default' => 'Küçə, ev nömrəsi'],
            ['key' => 'home_form_submit', 'label' => 'Hero forma düyməsi', 'default' => 'Usta Çağır – Pulsuz'],
            ['key' => 'home_form_privacy', 'label' => 'Forma gizlilik mətni', 'default' => 'Məlumatlarınız tam gizli saxlanılır'],
            ['key' => 'home_cta_whatsapp_btn', 'label' => 'CTA WhatsApp düyməsi', 'default' => 'WhatsApp'],
            ['key' => 'home_contact_service_label', 'label' => 'Əlaqə formu: Xidmət', 'default' => 'Xidmət'],
            ['key' => 'home_contact_note_label', 'label' => 'Əlaqə formu: Qeyd', 'default' => 'Qeyd'],
            ['key' => 'home_contact_note_placeholder', 'label' => 'Əlaqə formu: Qeyd placeholder', 'default' => 'Problem haqqında qısaca yazın...'],
            ['key' => 'home_contact_submit', 'label' => 'Əlaqə formu düyməsi', 'default' => 'Müraciət göndər →'],
            ['key' => 'alert_success', 'label' => 'JS: Uğurlu müraciət mətni', 'default' => 'Müraciətiniz qəbul edildi! Operator sizinlə ən qısa zamanda əlaqə saxlayacaq.', 'type' => 'textarea'],
            ['key' => 'alert_phone_required', 'label' => 'JS: Telefon vacib mətni', 'default' => 'Zəhmət olmasa telefon nömrənizi daxil edin.'],
            ['key' => 'alert_generic_error', 'label' => 'JS: Ümumi xəta mətni', 'default' => 'Xəta baş verdi. Zəhmət olmasa birbaşa zəng edin.'],
        ],

        'Xidmətlər Səhifəsi' => [
            ['key' => 'services_page_title', 'label' => 'Xidmətlər: H1', 'default' => 'Xidmətlərimiz'],
            ['key' => 'services_page_desc', 'label' => 'Xidmətlər: təsvir', 'default' => 'Bakıda bütün ev texnikasının peşəkar təmiri. 12 xidmət növü, 40+ marka, pulsuz diaqnostika.', 'type' => 'textarea'],
            ['key' => 'services_card_from', 'label' => 'Kart qiymət suffix', 'default' => 'AZN-dən başlayır'],
            ['key' => 'services_card_warranty', 'label' => 'Kart zəmanət', 'default' => '12 ay zəmanət'],
            ['key' => 'services_card_more', 'label' => 'Kart ətraflı', 'default' => 'Ətraflı →'],
            ['key' => 'services_cta_title', 'label' => 'Xidmətlər CTA başlıq', 'default' => 'Texnikanız xarabdır?'],
            ['key' => 'services_cta_desc', 'label' => 'Xidmətlər CTA təsvir', 'default' => 'İndi zəng edin, 2 saata usta evinizə gəlsin. Pulsuz diaqnostika, 12 ay zəmanət.', 'type' => 'textarea'],
            ['key' => 'services_cta_order_btn', 'label' => 'Xidmətlər CTA düymə', 'default' => 'Sifariş ver →'],
        ],

        'Xidmət Detalı' => [
            ['key' => 'service_show_badge_diagnosis', 'label' => 'Hero feature 1', 'default' => 'Pulsuz diaqnostika'],
            ['key' => 'service_show_badge_warranty', 'label' => 'Hero feature 2', 'default' => '12 ay yazılı zəmanət'],
            ['key' => 'service_show_badge_fast', 'label' => 'Hero feature 3', 'default' => 'Sifarişdən 2 saata usta'],
            ['key' => 'service_show_badge_parts', 'label' => 'Hero feature 4', 'default' => 'Orijinal ehtiyat hissələri'],
            ['key' => 'service_show_call_btn', 'label' => 'Hero zəng düyməsi', 'default' => '📞 Zəng et'],
            ['key' => 'service_show_order_btn', 'label' => 'Hero sifariş düyməsi', 'default' => 'Sifariş ver →'],
            ['key' => 'service_show_price_label', 'label' => 'Qiymət badge etiketi', 'default' => 'Başlanğıc qiymət'],
            ['key' => 'service_show_form_title', 'label' => 'Form başlıq', 'default' => 'Sifariş ver'],
            ['key' => 'service_show_form_subtitle', 'label' => 'Form subtitle', 'default' => 'Pulsuz diaqnostika + 12 ay zəmanət'],
            ['key' => 'service_show_problem_placeholder', 'label' => 'Form problem placeholder', 'default' => 'Problemin qısa təsviri...'],
            ['key' => 'service_show_problem_label', 'label' => 'Problem label', 'default' => 'Problemlər'],
            ['key' => 'service_show_problem_title', 'label' => 'Problem başlıq', 'default' => 'Hansı problemləri həll edirik?'],
            ['key' => 'service_show_process_label', 'label' => 'Proses label', 'default' => 'Proses'],
            ['key' => 'service_show_process_title', 'label' => 'Proses başlıq', 'default' => 'Necə işləyirik?'],
            ['key' => 'service_show_process_desc', 'label' => 'Proses təsvir', 'default' => 'Sadə, şəffaf, rahat. Sifarişdən işin tamamlanmasına qədər 4 addım.', 'type' => 'textarea'],
            ['key' => 'service_show_step1_title', 'label' => 'Addım 1 başlıq', 'default' => 'Zəng / Sifariş'],
            ['key' => 'service_show_step1_desc', 'label' => 'Addım 1 təsvir', 'default' => 'Zəng edin və ya formu doldurun. Operator 5 dəqiqəyə cavab verir.', 'type' => 'textarea'],
            ['key' => 'service_show_step2_title', 'label' => 'Addım 2 başlıq', 'default' => 'Usta gəlir'],
            ['key' => 'service_show_step2_desc', 'label' => 'Addım 2 təsvir', 'default' => '1-2 saata sertifikatlı usta evinizə gəlir.', 'type' => 'textarea'],
            ['key' => 'service_show_step3_title', 'label' => 'Addım 3 başlıq', 'default' => 'Pulsuz diaqnostika'],
            ['key' => 'service_show_step3_desc', 'label' => 'Addım 3 təsvir', 'default' => 'Problem müəyyən edilir, qiymət söylənir. Razılıq olmasa ödəniş yoxdur.', 'type' => 'textarea'],
            ['key' => 'service_show_step4_title', 'label' => 'Addım 4 başlıq', 'default' => 'Təmir + Zəmanət'],
            ['key' => 'service_show_step4_desc', 'label' => 'Addım 4 təsvir', 'default' => 'İş tamamlanır, 12 aylıq yazılı zəmanət verilir.', 'type' => 'textarea'],
            ['key' => 'service_show_adv_label', 'label' => 'Üstünlüklər label', 'default' => '⭐ Üstünlüklər'],
            ['key' => 'service_show_adv1_title', 'label' => 'Üstünlük 1 başlıq', 'default' => 'Sərfəli qiymət'],
            ['key' => 'service_show_adv1_desc', 'label' => 'Üstünlük 1 təsvir', 'default' => ':price AZN-dən başlayan qiymətlər. Gizli ödəniş yoxdur.', 'type' => 'textarea'],
            ['key' => 'service_show_adv2_title', 'label' => 'Üstünlük 2 başlıq', 'default' => '12 ay zəmanət'],
            ['key' => 'service_show_adv2_desc', 'label' => 'Üstünlük 2 təsvir', 'default' => 'Bütün işlərə yazılı zəmanət. Eyni problem yenidən olarsa – pulsuz.', 'type' => 'textarea'],
            ['key' => 'service_show_adv3_title', 'label' => 'Üstünlük 3 başlıq', 'default' => 'Orijinal hissələr'],
            ['key' => 'service_show_adv3_desc', 'label' => 'Üstünlük 3 təsvir', 'default' => 'Yalnız orijinal ehtiyat hissələri. Keyfiyyətsiz hissə istifadə olunmur.', 'type' => 'textarea'],
            ['key' => 'service_show_adv4_title', 'label' => 'Üstünlük 4 başlıq', 'default' => 'Peşəkar ustalar'],
            ['key' => 'service_show_adv4_desc', 'label' => 'Üstünlük 4 təsvir', 'default' => '4+ il təcrübəsi olan sertifikatlı ustalar. Hər usta sahə mütəxəssisidir.', 'type' => 'textarea'],
            ['key' => 'service_show_brands_label', 'label' => 'Brendlər label', 'default' => '🤝 Brendlər'],
            ['key' => 'service_show_brands_title', 'label' => 'Brendlər başlıq', 'default' => 'Hansı markaları təmir edirik?'],
            ['key' => 'service_show_brands_desc', 'label' => 'Brendlər təsvir', 'default' => ':service üzrə xidmət göstərdiyimiz aparıcı dünya markaları.', 'type' => 'textarea'],
            ['key' => 'service_show_faq_title', 'label' => 'FAQ başlıq', 'default' => 'Tez-tez verilən suallar'],
            ['key' => 'service_show_other_label', 'label' => 'Digər xidmətlər label', 'default' => '🔧 Digər xidmətlər'],
            ['key' => 'service_show_other_title', 'label' => 'Digər xidmətlər başlıq', 'default' => 'Digər xidmətlərimiz'],
            ['key' => 'service_show_cta_suffix', 'label' => 'CTA başlıq sonu', 'default' => 'üçün indi usta çağırın!'],
            ['key' => 'service_show_cta_desc', 'label' => 'CTA təsvir', 'default' => 'Pulsuz diaqnostika, :price AZN-dən başlayan qiymətlər, 12 ay zəmanət. Bakının bütün rayonlarına gedirik.', 'type' => 'textarea'],
        ],

        'Portfolio' => [
            ['key' => 'portfolio_title', 'label' => 'Portfolio H1', 'default' => 'Bizim işlərimiz'],
            ['key' => 'portfolio_desc', 'label' => 'Portfolio təsvir', 'default' => 'Hər iş öz sözünü özü danışır. Gördüyümüz təmirlərdən seçmə nümunələr.', 'type' => 'textarea'],
            ['key' => 'portfolio_filter_all', 'label' => 'Filter: hamısı', 'default' => 'Hamısı'],
            ['key' => 'portfolio_empty_title', 'label' => 'Boş portfolio mətni', 'default' => 'Portfolio hələ əlavə edilməyib.'],
            ['key' => 'portfolio_video_play_aria', 'label' => 'Video oynat aria-label', 'default' => 'Videonu oynat'],
            ['key' => 'portfolio_modal_close_aria', 'label' => 'Modal bağla aria-label', 'default' => 'Bağla'],
            ['key' => 'portfolio_badge_shorts', 'label' => 'YouTube Shorts badge', 'default' => 'Shorts'],
            ['key' => 'portfolio_badge_youtube', 'label' => 'YouTube badge', 'default' => 'YouTube'],
        ],

        'Əlaqə və Haqqımızda Səhifələri' => [
            ['key' => 'about_breadcrumb_home', 'label' => 'About breadcrumb home', 'default' => 'Ana səhifə'],
            ['key' => 'about_team_label', 'label' => 'About komanda label', 'default' => '👨‍🔧 Komanda'],
            ['key' => 'about_cert_label', 'label' => 'About sertifikat label', 'default' => '📜 Sertifikatlar'],
            ['key' => 'about_cert_title', 'label' => 'About sertifikat başlıq', 'default' => 'Rəsmi sertifikatlar'],
            ['key' => 'about_cert_desc', 'label' => 'About sertifikat təsvir', 'default' => 'Ustalarımız dünya markalarının rəsmi xidmət mərkəzlərindən sertifikat almışdır.', 'type' => 'textarea'],
            ['key' => 'about_cert_suffix', 'label' => 'Sertifikat kart suffix', 'default' => 'Rəsmi Servis Sertifikatı'],
            ['key' => 'about_team_empty', 'label' => 'Komanda boş mətni', 'default' => 'Komanda üzvü əlavə edilməyib.'],
            ['key' => 'about_cta_order_btn', 'label' => 'About CTA düymə', 'default' => 'Sifariş ver →'],
            ['key' => 'contact_breadcrumb_label', 'label' => 'Contact breadcrumb', 'default' => 'Əlaqə'],
            ['key' => 'contact_social_title', 'label' => 'Contact sosial başlıq', 'default' => 'Sosial şəbəkələr'],
            ['key' => 'contact_form_submit', 'label' => 'Contact form düymə', 'default' => 'Müraciət Göndər →'],
            ['key' => 'contact_map_office_title', 'label' => 'Map fallback başlıq', 'default' => 'USTA.BİZ.AZ Mərkəzi Ofis'],
        ],

        'Texniki Baxım' => [
            ['key' => 'maintenance_badge', 'label' => 'Badge mətni', 'default' => 'Texniki baxım rejimi'],
            ['key' => 'maintenance_title', 'label' => 'Başlıq', 'default' => 'Sayt üzərində <span>işlər</span> aparılır'],
            ['key' => 'maintenance_desc', 'label' => 'Təsvir', 'default' => 'Hal-hazırda saytımız yeniləmə prosesindədir.<br>Tezliklə yenidən xidmətinizdə olacağıq.', 'type' => 'textarea'],
            ['key' => 'maintenance_call_label', 'label' => 'Zəng etiketi', 'default' => 'Təcili olaraq zəng edin:'],
        ],
    ],
];
